from pydantic import BaseModel, Field
from typing import List, Literal, Optional
import pandas as pd
from datetime import datetime

class MarketData(BaseModel):
    """
    Holds aggregated market data for a specific ticker.

    Attributes:
        ticker (str): The stock ticker symbol.
        ohlcv (pd.DataFrame): DataFrame containing Open, High, Low, Close, Volume data.
        rsi (float): The calculated Relative Strength Index (RSI).
        ema_50 (float): The calculated 50-period Exponential Moving Average.
        current_price (float): The most recent price.
    """
    ticker: str
    ohlcv: pd.DataFrame
    rsi: float = Field(..., description="Relative Strength Index")
    ema_50: float = Field(..., description="50-period Exponential Moving Average")
    current_price: float

    class Config:
        arbitrary_types_allowed = True


class NewsItem(BaseModel):
    """
    Represents a single news article.

    Attributes:
        headline (str): The title of the news article.
        url (str): The URL to the full article.
        source (str): The source of the news (e.g., 'Reuters').
        date (datetime): The publication date and time.
    """
    headline: str
    url: str
    source: str
    date: datetime


class TradeSignal(BaseModel):
    """
    Represents the trading signal generated by the LLM.

    Attributes:
        signal (Literal["Buy", "Sell", "Hold"]): The recommended action.
        confidence (float): The confidence level of the signal, from 0.0 to 1.0.
        reasoning (str): The detailed explanation for the recommendation.
        stop_loss (Optional[float]): An optional stop-loss price recommendation.
    """
    signal: Literal["Buy", "Sell", "Hold"]
    confidence: float = Field(..., ge=0.0, le=1.0)
    reasoning: str
    stop_loss: Optional[float] = None
